% Fredrik Tåkvist
% ---------------
% make the buttons and the emergency and door lamps
function mk_controls()
    global floorPos figH btn1H btn2H btn3H btn4H lightDH lightEH buttons btnSH
    buttonSize = .1;    % size of floor buttons
    % position of floor button 1
    buttonPos = [.4 floorPos(2)+(floorPos(4)-buttonSize)/2 ...
                 buttonSize buttonSize];
    
    % create buttons
    btn1H = uicontrol(figH, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', buttonPos, ...
        'String', '1', ...
        'Callback', {@ext_buttons, 1});
    btn2H = uicontrol(figH, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', buttonPos + [0 floorPos(4) 0 0], ...
        'String', '2', ...
        'Callback', {@ext_buttons, 2});
    btn3H = uicontrol(figH, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', buttonPos + [0 floorPos(4)*2 0 0], ...
        'String', '3', ...
        'Callback', {@ext_buttons, 3});
    btn4H = uicontrol(figH, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', buttonPos + [0 floorPos(4)*3 0 0], ...
        'String', '4', ...
        'Callback', {@ext_buttons, 4});
    btn5H = uicontrol(figH, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', buttonPos + [0 floorPos(4)*4 0 0], ...
        'String', '5', ...
        'Callback', {@ext_buttons, 5});
    
    btnEH = uicontrol(figH, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [.1 .1 .2 .1], ...
        'String', 'Emergency', ...
        'Callback', {@ext_buttons, 6});
    btnSH = uicontrol(figH, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [.1 .25, .2 .1], ...
        'String', 'Inject Error', ...
        'BackgroundColor', 'green', ...
        'Callback', {@ext_buttons, 7});
    
    % create emergency and door lamps, with descriptive text
    lightEH = annotation('Ellipse', ...
        'Parent', figH, ...
        'Position', [.15 .4 .1 .1]);
    annotation('textbox', ...
        'Parent', figH, ...
        'Position', [.1 .5 .2 .1], ...
        'String', 'Emergency', ...
        'LineStyle', 'none', ...
        'HorizontalAlignment', 'center');

    lightDH = annotation('Ellipse', ...
        'Parent', figH, ...
        'Position', [.15 .7 .1 .1]);
    annotation('textbox', ...
        'Parent', figH, ...
        'Position', [.1 .8 .2 .1], ...
        'String', 'Doors', ...
        'LineStyle', 'none', ...
        'HorizontalAlignment', 'center');
    
    % set initial state of buttons
    buttons = [0 0 0 0 0 0 0];
end

